// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateCheckResult>;

export function CheckToken(arg1:string):Promise<main.CheckTokenResponse>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetHWID():Promise<string>;

export function GetMonitorData():Promise<main.MonitorResponse>;

export function GetRefreshDelay():Promise<number>;

export function InstallUpdate(arg1:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<main.AuthResponse>;

export function OpenBrowser(arg1:string):Promise<void>;

export function Register(arg1:string,arg2:string):Promise<main.RegisterResponse>;

export function UpdateConfig(arg1:string,arg2:number):Promise<void>;
