// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckToken(arg1) {
    return window['go']['main']['App']['CheckToken'](arg1);
}

export function GetConfig() {
    return window['go']['main']['App']['GetConfig']();
}

export function GetHWID() {
    return window['go']['main']['App']['GetHWID']();
}

export function GetMonitorData() {
    return window['go']['main']['App']['GetMonitorData']();
}

export function GetRefreshDelay() {
    return window['go']['main']['App']['GetRefreshDelay']();
}

export function Login(arg1, arg2) {
    return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
    return window['go']['main']['App']['Register'](arg1, arg2);
}

export function UpdateConfig(arg1, arg2) {
    return window['go']['main']['App']['UpdateConfig'](arg1, arg2);
}
