// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main } from '../models';

export function CheckToken(arg1: string): Promise<main.CheckTokenResponse>;

export function GetConfig(): Promise<main.Config>;

export function GetHWID(): Promise<string>;

export function GetMonitorData(): Promise<main.MonitorResponse>;

export function GetRefreshDelay(): Promise<number>;

export function Login(arg1: string, arg2: string): Promise<main.AuthResponse>;

export function Register(arg1: string, arg2: string): Promise<main.RegisterResponse>;

export function UpdateConfig(arg1: string, arg2: number): Promise<void>;
